//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSPERSONALES
    {
        public DATOSPERSONALES()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public string VCEDULA { get; set; }
        public string VNOMBRE { get; set; }
        public string VPRIMERAPELLIDO { get; set; }
        public string VSEGUNDOPELLIDO { get; set; }
        public System.DateTime DTFECHANACIMIENTO { get; set; }
        public string VGENERO { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
