//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICO
    {
        public DIAGNOSTICO()
        {
            this.CONTRAINDICACION_DIAGNOSTICO = new HashSet<CONTRAINDICACION_DIAGNOSTICO>();
            this.INDICACION_DIAGNOSTICO = new HashSet<INDICACION_DIAGNOSTICO>();
            this.PACIENTE = new HashSet<PACIENTE>();
            this.PADECIMIENTO = new HashSet<PADECIMIENTO>();
            this.SINTOMA = new HashSet<SINTOMA>();
        }
    
        public int IID { get; set; }
        public string VDIAGNOSTICO { get; set; }
        public string TDESCRIPCION { get; set; }
    
        public virtual ICollection<CONTRAINDICACION_DIAGNOSTICO> CONTRAINDICACION_DIAGNOSTICO { get; set; }
        public virtual DIAGNOSTICO DIAGNOSTICO1 { get; set; }
        public virtual DIAGNOSTICO DIAGNOSTICO2 { get; set; }
        public virtual ICollection<INDICACION_DIAGNOSTICO> INDICACION_DIAGNOSTICO { get; set; }
        public virtual ICollection<PACIENTE> PACIENTE { get; set; }
        public virtual ICollection<PADECIMIENTO> PADECIMIENTO { get; set; }
        public virtual ICollection<SINTOMA> SINTOMA { get; set; }
    }
}
