//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PADECIMIENTO
    {
        public int IID { get; set; }
        public string IIDPACIENTE { get; set; }
        public int IIDDIAGNOSTICO { get; set; }
        public System.DateTime DTFECHAINICIO { get; set; }
        public bool BESTADO { get; set; }
        public Nullable<System.DateTime> DTFECHAFINALIZACION { get; set; }
    
        public virtual DIAGNOSTICO DIAGNOSTICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
