//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINTOMA
    {
        public SINTOMA()
        {
            this.CONTRAINDICACION_SINTOMA = new HashSet<CONTRAINDICACION_SINTOMA>();
            this.INDICACION_SINTOMA = new HashSet<INDICACION_SINTOMA>();
            this.PACIENTE_SINTOMA = new HashSet<PACIENTE_SINTOMA>();
            this.DIAGNOSTICO = new HashSet<DIAGNOSTICO>();
            this.MEDICAMENTO = new HashSet<MEDICAMENTO>();
        }
    
        public int IID { get; set; }
        public string VEFECTO { get; set; }
        public string VDESCRIPCION { get; set; }
    
        public virtual ICollection<CONTRAINDICACION_SINTOMA> CONTRAINDICACION_SINTOMA { get; set; }
        public virtual ICollection<INDICACION_SINTOMA> INDICACION_SINTOMA { get; set; }
        public virtual ICollection<PACIENTE_SINTOMA> PACIENTE_SINTOMA { get; set; }
        public virtual ICollection<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public virtual ICollection<MEDICAMENTO> MEDICAMENTO { get; set; }
    }
}
