//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public string USUARIO1 { get; set; }
        public string PASSWORD { get; set; }
        public string IDDATOSPERSONALES { get; set; }
        public string VROL { get; set; }
    
        public virtual DATOSPERSONALES DATOSPERSONALES { get; set; }
    }
}
