//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIA_ADMINISTRACION
    {
        public VIA_ADMINISTRACION()
        {
            this.MEDICAMENTO = new HashSet<MEDICAMENTO>();
        }
    
        public int IID { get; set; }
        public string VNOMBRE { get; set; }
        public string VDESCRIPCION { get; set; }
    
        public virtual ICollection<MEDICAMENTO> MEDICAMENTO { get; set; }
    }
}
