//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaPacienteMedicamento
    {
        public string Cedula { get; set; }
        public string Medicamento { get; set; }
        public decimal Dosis { get; set; }
        public string Rango { get; set; }
        public string Via_Administracion { get; set; }
        public string Descripcion { get; set; }
    }
}
